[package]
name = "dual"
version = "0.1.0"
edition = "2024"

[dependencies]
glam = "0.31.0"
wgpu = "28.0.0"
winit = "0.30.12"
tokio = { version = "1", features = ["full"] }
env_logger = "0.11.8"
anyhow = "1.0.100"
